/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.pipeclamp.test;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Country { 
  CAN, USA, MEX, JAP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Country\",\"namespace\":\"com.pipeclamp.test\",\"symbols\":[\"CAN\",\"USA\",\"MEX\",\"JAP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
